### ISSUE TITLE
Add json input/output capability

### ISSUE THREAD

**Issue by robdmc** [robdmc/pandashells#10]

**Comment by vielmetti** [comment]
I'd recommend looking at the `jq` package as one way to get JSON input/output; it at the very minimum does a good job of going from CSV to JSON and vice versa.

https://github.com/stedolan/jq

**Comment by robdmc** [comment]
Yes.  I love jq.  The cool thing about Pandashells being a command line tool, is that it's super simple to do stuff like:

`cat file.json | jq [your options here] | p.df [your options here]`

**Comment by robdmc** [comment]
implemented
