### ISSUE TITLE
Declare optional dependencies

### ISSUE THREAD

**Issue by moreati** [robdmc/pandashells#21]
As mentioned on [HN](https://news.ycombinator.com/item?id=9992507) it would be good if the optional features (e.g. plotting) could be queried and installed explicitly. The usual way to do this is with the setuptools argument [`extras_require`](https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)

I've started a [branch](https://github.com/moreati/pandashells/tree/extras_require), for an eventual pull request

**Comment by robdmc** [comment]
I've created a new issue for this with my thoughts on how it should be broken down.  See #25
