### ISSUE TITLE
Add support for tab-delimited data

### ISSUE THREAD

**Issue by vellamike** [robdmc/pandashells#28]
It would be useful to have the ability to work with tab-delimited data (or indeed, select any delimiter).

**Comment by robdmc** [comment]
Tab delimited data is supported (i.e. white-space delimited).  If this is the type of data you mostly deal with, you can set it to be the default using the `p.config` tool

`cat my_tab_file.txt | p.df  -i table`

**Comment by vellamike** [comment]
that's great, thanks!
