### ISSUE TITLE
Error - "failed to create process“

### ISSUE THREAD

**Issue by xingjianpan** [robdmc/pandashells#30]
Hello,

I followed below steps to install pandashells, but when I tried to run any commands(i.e.  p.config), I would get the error message "failed to create process“.   Any ideas? Thanks!

OS: Windows 10.
Anaconda python2.7(64bit)

```shell
# Create and activate a new conda env for pandashells (optional) 
conda create -n pandashells python=2.7 anaconda
. activate pandashells

# seaborn and mpld3 only needed if you want to create plots
conda install seaborn
pip install mpld3

 
# installs all command line tools
pip install pandashells
```

**Comment by robdmc** [comment]
Hello.  Pandashells was designed to be used at the bash prompt.  As such, I would be surprised if it actually worked in a windows environment.  I'd be curious to know if anyone gets it to work under Windows with cygwin though.

I don't know how plugged in to the Python community you are, but most of the Pandashells capability is available by running pandas IPython Notebook, which I believe plays nicely with Windows.
