### ISSUE TITLE
Getting help?

### ISSUE THREAD

**Issue by jliberma** [robdmc/pandashells#39]
Is there a mailing list or other forum for getting usage help?

Cheers, Jacob

**Comment by robdmc** [comment]
Unfortunately, there is not.  I can answer a few questions here, but my response time may be a bit slow.  The usage very closely mirrors the Pandas library, so going through the Pandas tutorial may be useful.

http://pandas.pydata.org/pandas-docs/stable/tutorials.html

I'm going to close this issue, but feel free to continue commenting.
